### ISSUE TITLE
Remove /etc/apk from distroless images

### ISSUE THREAD

**Issue by skaegi** [distroless/static#15]
We're using Tekton and as part of our release process which in turn is now using `ghcr.io/distroless/static`. We do an image scan which has some simple OS detection which is getting baffled by the presence of...
```
> etc/apk/
> etc/apk/arch
> etc/apk/keys/
> etc/apk/keys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
> etc/apk/keys/alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub
> etc/apk/keys/alpine-devel@lists.alpinelinux.org-6165ee59.rsa.pub
> etc/apk/repositories
> etc/apk/world
```

I do not believe these are required to run anything and are present as an artifact of using apko to set things up. Could these folders be removed from the final image?

**Comment by kaniini** [comment]
apko retains those files intentionally (it is possible to use them to make additional edits to the generated filesystem later), why does Tekton need them removed?

**Comment by skaegi** [comment]
It's certainly not Tekton that "needs" them removed. Our image scanning tooling recognized that there was a difference when Tekton changed its base image from `gcr.io/distroless/static` to `ghcr.io/distroless/static` and in particular (incorrectly) flagged the `/etc/apk` folder as part of an Alpine OS that it did not know how to analyze for vulnerabilities. 

This issue is just making the observation that they are not needed at runtime. If they are serving as apkos record of what was installed then I can understand.

**Comment by kaniini** [comment]
Yes, the files in /etc/apk and /lib/apk are part of the apk database, and need to be preserved for tools that make use of the apkdb to function correctly.  We could remove the configuration side, but this would remove context that various tools (such as SCA/vulnerability scanners, or apk operating on the apkdb in a multistage build) use to process the image.

**Comment by kaniini** [comment]
(I agree this is kind of silly for static but if we remove this data, somebody else who is modifying the image or scanning it will likely ask for it back.)

**Comment by skaegi** [comment]
Thanks @kaniini -- closing.
